version: '3'
services:
  web: 
    build: 
      context: . # where to pull the image and files from 
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules 
      - .:/app
  
  tests: 
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes: 
      - /app/node_modules
      - .:/app 
    command: ["npm", "run", "test"]